import { z } from "zod";

export const exportRequestSchema = z.object({
  module: z.enum([
    "fundFlow",
    "dueBills",
    "wip",
    "contractors",
    "tenders",
    "paymentSchedules",
    "vehicleLogBook",
    "assets",
    "inOutRegister",
    "auditLogs",
    "tadaBills",
    "tasks",
    "clients",
    "staff",
    "masters_region",
    "masters_department",
    "masters_designation",
    "masters_state",
    "masters_city",
    "masters_platform",
    "masters_paymentType",
    "masters_assetCategory",
    "masters_assetMake",
    "masters_assetModel",
    "masters_orderMaster",
    "masters_workMaster",
    "masters_typeMaster",
    "masters_dprMaster",
    "masters_tsAaMaster",
    "masters_workOrderMaster",
    "masters_drawingMaster",
    "masters_contactMaster",
  ]),
  format: z.enum(["csv", "json", "xlsx"]),
});

export const importRequestSchema = z.object({
  module: z.enum([
    "fundFlow",
    "dueBills",
    "wip",
    "contractors",
    "tenders",
    "paymentSchedules",
    "vehicleLogBook",
    "assets",
    "inOutRegister",
    "tadaBills",
    "tasks",
    "clients",
    "staff",
    "masters_region",
    "masters_department",
    "masters_designation",
    "masters_state",
    "masters_city",
    "masters_platform",
    "masters_paymentType",
    "masters_assetCategory",
    "masters_assetMake",
    "masters_assetModel",
    "masters_orderMaster",
    "masters_workMaster",
    "masters_typeMaster",
    "masters_dprMaster",
    "masters_tsAaMaster",
    "masters_workOrderMaster",
    "masters_drawingMaster",
    "masters_contactMaster",
  ]),
  format: z.enum(["csv", "json"]),
  data: z.string().min(1),
});

export type ExportRequestInput = z.infer<typeof exportRequestSchema>;
export type ImportRequestInput = z.infer<typeof importRequestSchema>;
